### ISSUE TITLE
tesseract-build Scripts fail building tesseract 5.0.1 under macOS 11.6.3 on arm64

### ISSUE THREAD

**Issue by B-Michel** [hexdreamer/tesseract-build#9]
Provided Scripts build tesseract 4.1.1 perfectly, but fail trying to build tesseract 5.0.1

Building script fails with :
Undefined symbols for architecture arm64:
  "tesseract::IntSimdMatrix::intSimdMatrixNEON", referenced from:
      tesseract::SIMDDetect::SIMDDetect() in libtesseract.a(libtesseract_la-simddetect.o)
      tesseract::SIMDDetect::Update() in libtesseract.a(libtesseract_la-simddetect.o)
  "tesseract::DotProductNEON(float const*, float const*, int)", referenced from:
      tesseract::SIMDDetect::SIMDDetect() in libtesseract.a(libtesseract_la-simddetect.o)
      tesseract::SIMDDetect::Update() in libtesseract.a(libtesseract_la-simddetect.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [tesseract] Error 1
make: *** [all-recursive] Error 1

**Comment by hexdreamer** [comment]
This fork is now defunct. Please use https://github.com/pokkinandpup/TesseractBuild as the official version.

**Comment by hexdreamer** [comment]
The current version of TesseractBuild is compatible with macOS 12.2.

**Comment by B-Michel** [comment]
Thank you, everything is building/running now without problems under mac0S 11.6.3
